### ISSUE TITLE
Module not found error when exporting to Kotlin on V1.0.0+

### ISSUE THREAD

**Issue by theomichail** [frankois944/spm4Kmp#244]
## 🐛 Describe the bug

After upgrading from v0.11.3 to anything afterwards (v1.0.0-v1.4.2) we're seeing an error when trying to include the `DatadocCore` swift library with `exportToKotlin` set to true. This library previously worked fine when using 0.11.3 but I can no longer verify this as I've had to upgrade to Xcode 26.

It may be worth noting that the `DatadogInternal` files are present in the scratch directory within the module's build folder (screenshot attached below).

TIA for any help 🙂 

## ⚠️ Current behavior

When trying to sync or build the project (reproducer project attached below) I get the following error:
```
> Task :composeApp:cinteropDatadogCoreDatadogBridgeIosArm64 FAILED
Exception in thread "main" java.lang.Error: /Users/theomichail/IdeaProjects/spmforkmpdatadogreproducer/composeApp/build/spmKmpPlugin/DatadogBridge/scratch/arm64-apple-ios/release/DatadogCore.build/include/DatadogCore-Swift.h:282:9: fatal error: module 'DatadogInternal' not found
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:80)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:15)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:566)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:306)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLibSafe(main.kt:242)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.access$processCLibSafe(main.kt:1)
        at org.jetbrains.kotlin.native.interop.gen.jvm.Interop.interop(main.kt:101)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:49)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:23)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:40)
```

## ✅ Expected behavior

The module should build without errors

## 💣 Steps to reproduce

Open the following project and sync or run `./gradlew composeApp:build`

[reproducer.zip](https://github.com/user-attachments/files/24473817/reproducer.zip)

## 📷 Screenshots

<img width="474" height="639" alt="Image" src="https://github.com/user-attachments/assets/1c7e44d2-f078-481b-843d-00cdcf86184d" />

## 📱 Tech info
 - Device: Macbook Pro
 - OS: MacOS 26.2
 - Library: 1.0.0-1.4.2
 - Xcode :  26.2
 - Gradle: 8.14.3 or 9.1.0
 - Android Gradle Plugin: 8.11.2
 - Kotlin: 2.2.21

**Comment by frankois944** [comment]
Hello,
thanks for making this issue, I have found the problem.
I will fix it asap.

**Comment by code-absolute** [comment]
Hello, 
I've encoutered a similar problem with Adobe libraries such as [AEPCore](https://github.com/adobe/aepsdk-core-ios.git) and [AEPAnalytics](https://github.com/adobe/aepsdk-analytics-ios.git)
I'm wondering if the fix that you create will resolve this issue as well.

**Comment by theomichail** [comment]
> Hello,
> thanks for making this issue, I have found the problem.
> I will fix it asap.
> 
> 

Awesome, thank you for getting to that so quickly!

**Comment by frankois944** [comment]
Fixed in [1.4.3](https://github.com/frankois944/spm4Kmp/releases/tag/1.4.3)

**Comment by frankois944** [comment]
> Hello, I've encoutered a similar problem with Adobe libraries such as [AEPCore](https://github.com/adobe/aepsdk-core-ios.git) and [AEPAnalytics](https://github.com/adobe/aepsdk-analytics-ios.git) I'm wondering if the fix that you create will resolve this issue as well.

@code-absolute try the new version, if it's not working, make a new issue.

Thanks

**Comment by code-absolute** [comment]
The new version fixed my issue.

Thanks!
