### ISSUE TITLE
Error after upgrading to Compose Multiplatform 1.9.1

### ISSUE THREAD

**Issue by ivnsch** [frankois944/spm4Kmp#192]
After upgrading from Compose Multiplatform 1.8.1 to 1.9.1, iOS compilation fails with a duplicate symbol error during the linking phase when using Sentry via Swift Package Manager with the spmForKmp plugin. This configuration worked without issues on Compose Multiplatform 1.8.1.

> w: KLIB resolver: The same 'unique_name=savedstate-compose_nonAndroidMain' found in more than one library: 
> /path/to/build/kotlinTransformedMetadataLibraries/commonMain/org.jetbrains.androidx.savedstate-savedstate-compose-1.3.4-nonAndroidMain-JasBlA.klib, 
> /path/to/build/kotlinTransformedMetadataLibraries/nativeMain/androidx.savedstate-savedstate-compose-1.3.3-nonAndroidMain-9pLK_g.klib
> 
> > Task :composeApp:linkDebugFrameworkIosArm64
> e: Compilation failed: IrPropertySymbolImpl is already bound. Signature: androidx.savedstate.compose/LocalSavedStateRegistryOwner|{}LocalSavedStateRegistryOwner[0]. Owner: PROPERTY name:LocalSavedStateRegistryOwner visibility:public modality:FINAL [val]
> 
> e: java.lang.IllegalStateException: IrPropertySymbolImpl is already bound. Signature: androidx.savedstate.compose/LocalSavedStateRegistryOwner|{}LocalSavedStateRegistryOwner[0]. Owner: PROPERTY name:LocalSavedStateRegistryOwner visibility:public modality:FINAL [val]

config
```
kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }

        iosTarget.compilations {
            val main by getting {
                cinterops.create("nativeIosShared")
            }
        }
    }
}

swiftPackageConfig {
    create("nativeIosShared") {
        dependency {
            remotePackageVersion(
                url = uri("https://github.com/getsentry/sentry-cocoa"),
                version = "8.56.0",
                products = {
                    add("Sentry")
                },
            )
        }
    }
}
```

**Comment by frankois944** [comment]
Hello, 
I don't see any related **native** linking issue in your errors.

**Comment by frankois944** [comment]
That's a CMP error, not a cinterop/native error.
