### ISSUE TITLE
Supporting binary targets and conditional dependencies

### ISSUE THREAD

**Issue by markst** [frankois944/spm4Kmp#98]
Hey @frankois944, such great work has gone into this.

I wanted to share some encounters I had when using:
https://github.com/segment-integrations/swift-create-xcframework

I had some dependencies which uses conditional dependencies and binary targets which prevented me from compiling my Swift Package into a distributable XCFramework. 

I'm curious to try my same Swift Package using spm4Kmp, so thought I'd crate an issue to share my tests.

**Comment by markst** [comment]
The relevant validation occurs here incase it's helpful:

https://github.com/segment-integrations/swift-create-xcframework/blob/33079d31ca8f93a025d9494aca159407656f7b23/Sources/CreateXCFramework/PackageInfo.swift#L145

**Comment by frankois944** [comment]
Hi, thanks for your feedback.

What kind of conditional dependency, [by target platform](https://frankois944.github.io/spm4Kmp/usages/multiTarget/)?

**Comment by frankois944** [comment]
FYI: binary target [are already supported ](https://frankois944.github.io/spm4Kmp/bridgeWithDependencies/#__tabbed_1_5)

**Comment by markst** [comment]
Nice, seems like you've covered a lot of ground 👏


I mean within the Swift Package, for instance:
```swift
.targetItem(name: "xxx", condition: .when(platforms: [.iOS]))
```
or
```swift
.define("MOCKING", .when(configuration: .debug)),
```

Might add that we use plugins also, so will give a try with the following:
```swift
.plugin(name: "XCStringsToolPlugin", package: "xcstrings-tool-plugin")
```

**Comment by frankois944** [comment]
If you want to have a really complex package, create a local package and declare it inside the plugin config instead of using the bridge. You will have the freedom to do what you want.

The main goal of the bridge is to be a bridge, not a full library (where it's kind of difficult to write/test code), but I can add some feature to change the behavior of the bridge with KMP.

Also, SPM Manifest is huge, some like [Firebase](https://github.com/firebase/firebase-ios-sdk/blob/main/Package.swift) or [AppMetrica](https://github.com/appmetrica/appmetrica-sdk-ios/blob/main/Package.swift) are highly dynamic.

**Comment by markst** [comment]
Yes local or remote package is the way I would go rather than bridge.

Just FYI here's example outputs from my package when using mentioned swift-create-xcframework:
```
Error: Xcode project generation is not supported by Swift Package Manager for packages that contain binary targets.These binary targets were detected: GoogleCast, xcstrings-tool, ABCAssets, Lottie
Warning: Xcode project generation does not support conditional target dependencies, so the generated project may not build successfully.These targets contain conditional dependencies: DLSComponents
```

**Comment by markst** [comment]
Exception raised when gradle syncing, possibly I need to compiler flag my tests?
```
Exception in thread "main" java.lang.Error: MediaPlayer-Swift.h:282:9: fatal error: module 'XCTest' not found
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:80)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:15)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:562)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:308)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLibSafe(main.kt:244)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.access$processCLibSafe(main.kt:1)
	at org.jetbrains.kotlin.native.interop.gen.jvm.Interop.interop(main.kt:102)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:48)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:23)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:44)
```

**Comment by frankois944** [comment]
> Yes local or remote package is the way I would go rather than bridge.
> 
> Just FYI here's example outputs from my package when using mentioned swift-create-xcframework:
> 
> ```
> Error: Xcode project generation is not supported by Swift Package Manager for packages that contain binary targets.These binary targets were detected: GoogleCast, xcstrings-tool, ABCAssets, Lottie
> Warning: Xcode project generation does not support conditional target dependencies, so the generated project may not build successfully.These targets contain conditional dependencies: DLSComponents
> ```

[Create-xcframework](https://github.com/segment-integrations/swift-create-xcframework) is not part of spmForKmp, it's for other usage, it's not even related to it.

You should follow the Kotlin API for creating a XCFramework.

I [did try to create](https://github.com/frankois944/spmForKmpWithDistribution/blob/835daf4c5f9e0901b4f960491e98833e1b8a3b98/library/build.gradle.kts#L33-L52) an xcframework with the plugin, but it kind of difficult.

**Comment by frankois944** [comment]
> Exception raised when gradle syncing, possibly I need to compiler flag my tests?
> 
> ```
> Exception in thread "main" java.lang.Error: MediaPlayer-Swift.h:282:9: fatal error: module 'XCTest' not found
> 	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:80)
> 	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:15)
> 	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:562)
> 	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:308)
> 	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLibSafe(main.kt:244)
> 	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.access$processCLibSafe(main.kt:1)
> 	at org.jetbrains.kotlin.native.interop.gen.jvm.Interop.interop(main.kt:102)
> 	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:48)
> 	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:23)
> 	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:44)
> ```
> 
> Seems our Mockable library links `xctest-dynamic-overlay`, so will try removing that temporarily.
> 
> Edit: `CombineExt` is also linking!

you have a bad configuration somewhere.

**Comment by markst** [comment]
>[Create-xcframework](https://github.com/segment-integrations/swift-create-xcframework) is not part of spmForKmp, it's for other usage, it's not even related to it.
Well aware of that, just both build Package.swift to a binary so thought it's worth sharing some hurdles. 

> you have a bad configuration somewhere.

Well the Package.swift builds fine independently. I've removed all `XCTest` imports, so it's just the `xctest-dynamic-overlay` linkage which may be including the `XCTest` import in my Swift generated header. 

Will do more poking around.
